# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  api:
    image: api
    restart: always
    build:
      context: .
      dockerfile: Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - ${SERVER_PORT}:5268
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False
      - Jwt__Key=${Jwt_Key}
      - BlobStorage__ConnectionString=${BlobStorage__ConnectionString}
      - BlobStorage__ContainerName=${BlobStorage__ContainerName}
      - BlobStorage__DefaultAvatarUrl=${BlobStorage__DefaultAvatarUrl}
      - FEED__ADFREQUENCY=${FEED_ADFREQUENCY}
      - FEED__VIEWCOOLDOWNHOURS=${FEED_VIEWCOOLDOWNHOURS}
      - MODERATOR_EMAILS=${MODERATOR_EMAILS}

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: driprate-sqlserver
    restart: always
    ports:
      - ${DB_PORT}:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
